### ISSUE TITLE
Buat project planning

### ISSUE THREAD

**Issue by jufianto** [KongkowITPekanbaru/masjid-network#3]
harus dibuat markdown file / page khusus untuk fitur apa aja yang akan ada di mesjid-network ini. 

beberapa fitur yang masih terpikirkan 

* pendataan aset mesjid 
* pencatatan kas mesjid 
* jadwal kajian 

beberapa micro yang terpikir 
* micro users (manajemen user login)
* micro jadwal kajian 
* micro pencatatan aset
* micro pencatatan kas

## Todoist 

* buat user stories (usecase)
* flowchart setiap proses

**Comment by ahmad-reza619** [comment]
Mungkin boleh tambahan ya kayak fitur jadwal solat mungkin 🤔

**Comment by jufianto** [comment]
> Mungkin boleh tambahan ya kayak fitur jadwal solat mungkin 🤔

kalau gitu cari api yang jadwal sholat setiap kota mungkin, btw nanti tujuannya juga biar bisa ditampilkan di layar besar gitu / monitor gitu
